name: Release Script
on: push

jobs:
  update-time:
    runs-on: ubuntu-latest
    name: Publish script
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: denolib/setup-deno@v1.3.0
      - run: |
          deno bundle map/src/index.ts map.js
          deno bundle check-update/src/index.ts check-update.js
      - name: Delete
        uses: ame-yu/action-delete-latest-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: $ {{ github.repository }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag_name: latest
          files: |
            map.js
            check-update.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
